/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import bancoDeDados.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.*;
import extra.Cpf;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

/**
 *
 * @author alunom
 */
public class inicial extends javax.swing.JFrame {

    Cpf cpf =new Cpf();
    TurmaBD turmabd = new TurmaBD();
    Turma turma = new Turma();
    ConvidadoBD convidadobd = new ConvidadoBD();
    Convidado convidado = new Convidado();
    ArrayList<Turma> listaTurma;
    int i = 0;

    public inicial() {
        initComponents();
        this.setSize(900,700);
        /*
        URL url = this.getClass().getResource("logoOurus.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(new ImageIcon("logoOurus.png"));
        */
        
        
        this.getContentPane().setBackground(new Color(255, 255, 255));

        this.setTitle("Feira de Curso CEET");

      //  atualizarBanco(-1);
        this.setLocationRelativeTo(null);
        cbxAluno.removeAllItems();
        
        listaTurma = turmabd.listadeTurma();
         for (Turma tur:listaTurma)
        {
            cbxAluno.addItem(tur.getNomeCurso()+"    -    "+tur.getTurno());
        }
       
      cbxEscolaridade.removeAllItems();
        cbxEscolaridade.addItem("Fundamental incompleto");
        cbxEscolaridade.addItem("Fundamental completo");
        cbxEscolaridade.addItem("Médio incompleto");
        cbxEscolaridade.addItem("Médio completo");
        cbxEscolaridade.addItem("Técnico incompleto");
        cbxEscolaridade.addItem("Técnico completo");
        cbxEscolaridade.addItem("Superior incompleto");
        cbxEscolaridade.addItem("Superior completo");
        

       // this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btCadastrarConvidado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        tfCPF = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfCelular = new javax.swing.JFormattedTextField();
        cbxEscolaridade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxAluno = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Feira");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vasco6_fw.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 10, 537, 182);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/feira3.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 205, 381, 477);

        btCadastrarConvidado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons 1/accept.png"))); // NOI18N
        btCadastrarConvidado.setText("Cadastrar Convidado");
        btCadastrarConvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarConvidadoActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarConvidado);
        btCadastrarConvidado.setBounds(640, 630, 160, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("<html>Nome<font color='red'>*</font>:</html>");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 320, 60, 20);
        getContentPane().add(tfNome);
        tfNome.setBounds(530, 320, 270, 30);

        try {
            tfCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCPF);
        tfCPF.setBounds(530, 350, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("<html>CPF<font color='red'>*</font>:</html>");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 350, 50, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("E-Mail:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 380, 50, 20);
        getContentPane().add(tfEmail);
        tfEmail.setBounds(530, 380, 210, 30);

        try {
            tfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfTelefone);
        tfTelefone.setBounds(530, 420, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Telefone:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 420, 70, 20);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("celular:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(420, 460, 60, 20);

        try {
            tfCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfCelular);
        tfCelular.setBounds(530, 470, 90, 30);

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cbxEscolaridade);
        cbxEscolaridade.setBounds(530, 520, 270, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Escolaridade:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 520, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Turma:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 560, 60, 20);

        cbxAluno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxAluno.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(cbxAluno);
        cbxAluno.setBounds(530, 560, 270, 30);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Convidado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 230, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarConvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarConvidadoActionPerformed
        // TODO add your handling code here:
        if (tfCPF.getText().trim().isEmpty() || tfNome.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Os campos com * sao \n \t obrigatorios");
        } else {
            if(cpf.cfp(tfCPF.getText()))
            {
            convidado.setCpf(tfCPF.getText());
            convidado.setEmail(tfEmail.getText());
            convidado.setEscolaridade(cbxEscolaridade.getSelectedItem() + "");
            convidado.setNome(tfNome.getText());
            convidado.setTelefone(tfTelefone.getText());
            convidado.setCelular(tfCelular.getText());

            convidadobd.cadastrarConvidado(listaTurma.get(cbxAluno.getSelectedIndex()), convidado);

            tfCPF.setText(null);
            tfEmail.setText(null);
            tfNome.setText(null);
            tfTelefone.setText(null);
            tfCelular.setText(null);
            }else
            {
                JOptionPane.showMessageDialog(rootPane, "CPF não e valido");
            }
        }
    }//GEN-LAST:event_btCadastrarConvidadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicial().setVisible(true);
            }
        });
    }

 /*   private void atualizarBanco(int idOrganizar) {

        cbxAluno.removeAllItems();
        listaTurma = turmabd.listadeTurma();

        for (Turma temp : listaTurma) {
            cbxAluno.addItem(temp.getNomeCurso()+" - " + temp.getCurso()+" - " + temp.getTurno());

        }

        if (idOrganizar != -1) {
            for (int i = 0; i < listaAlunos.size(); i++) {
                if (listaAlunos.get(i).getCodCurso() == idOrganizar) {
                    cbxAluno.setSelectedIndex(i);
                    break;
                }
            }
        }
    }
*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarConvidado;
    private javax.swing.JComboBox cbxAluno;
    private javax.swing.JComboBox cbxEscolaridade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField tfCPF;
    private javax.swing.JFormattedTextField tfCelular;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfNome;
    private javax.swing.JFormattedTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
